-- Metastores
CREATE DATABASE IF NOT EXISTS hive;
CREATE DATABASE IF NOT EXISTS iceberg;

CREATE USER IF NOT EXISTS 'hive'@'%' IDENTIFIED BY 'hivepass';
CREATE USER IF NOT EXISTS 'iceberg'@'%' IDENTIFIED BY 'icebergpass';

GRANT ALL PRIVILEGES ON hive.* TO 'hive'@'%';
GRANT ALL PRIVILEGES ON iceberg.* TO 'iceberg'@'%';

-- MySQL catalog
CREATE DATABASE IF NOT EXISTS iris;
CREATE USER IF NOT EXISTS 'trino'@'%' IDENTIFIED BY 'trinopass';
GRANT ALL PRIVILEGES ON iris.* TO 'trino'@'%';
